### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by cauvang32** [hihumanzone/Gemini-Discord-Bot#7]
I get this error when using node index.js or npm start while I still can install package normally (Ubuntu 24.04 LTS)
Node version: v18.20.4
Npm version: 10.7.0

**Comment by hihumanzone** [comment]
I'm not really sure what the issue is. I've tried searching and even asked ChatGPT, and found a few possible solutions. You might want to try those; they could help. I don't think the problem is related to the bot.

https://stackoverflow.com/questions/65631801/illegal-instructioncore-dumped-error-on-jetson-nano
https://chatgpt.com/share/fa16bfff-49d6-4970-89c2-b608fbdaeffc
